---
- name: update .bashrc file
  replace:
    dest: ~/.bashrc
    regexp: \\\[\\e]0;\$\{debian_chroot:\+\(\$debian_chroot\)\}\\u@\\h
    replace: '\[\e]0;${debian_chroot:+($debian_chroot)}{{ tab_name }}'
  tags:
    - rename-terminal-tab