---
- name: create rename-tab.sh file
  template:
    src: rename-tab.sh.j2
    dest: ~/bin/rename-tab.sh
  tags:
    - rename-terminal-tab

- name: add call to rename-tab.sh to .bashrc
  lineinfile:
    dest: ~/.bashrc
    line: ~/bin/rename-tab.sh
  tags:
    - rename-terminal-tab